### ISSUE TITLE
AWS Lambdaについて調べる

### ISSUE THREAD

**Issue by fuzzy-yusuke** [fuzzy-yusuke/tasks#11]
先輩から「Expressだと常時Expressサーバーを起動しておく必要があるのでサーバー代金も24時間分のお金がかかるけど、
例えばLambdaだとAPI実行したときに勝手にAWS側でDockerが起動して、関数の処理が終わると停止するから
関数の実行時間が1分とかでも起動してない時間のお金はかからない＝節約できるのでみんな使ってる、って状況」だとご教示いただいた
バックエンドはAWS Lambdaでやるのがベターなのか？
会社でもAWSの知見を共有するチームに入ったので、調べてみる

**Comment by fuzzy-yusuke** [comment]
Lambdaは関数の実行時間によってかかるお金が変動するもの
だが、無料枠の範囲がある
ブログ運営だけなら、この無料枠だけで良いのか？

https://www.fenet.jp/aws/column/aws-beginner/526/

**Comment by sena-v** [comment]
ブログ運用に絞ると、そもそも「どんなブログを作りたいのか？」を先に分解して考えた方がいい

1. アクセスしたユーザーからは投稿ができず、閲覧専用のブログ(コメントはメール等で受け取る)
2. アクセスしたユーザーからページ上に認証なしのコメントが投稿できるブログ
3. ログインをするとどんなユーザーでも記事が書き込めて、コメントも書き込みができるブログ

例えばこの中でどれがやりたいかをまず決めて、その上でなにが必要かを洗い出していくといいと思う
(パッと全体を見るとここが固まってないよう見えるから)

**Comment by fuzzy-yusuke** [comment]
> ブログ運用に絞ると、そもそも「どんなブログを作りたいのか？」を先に分解して考えた方がいい
> 
> 1. アクセスしたユーザーからは投稿ができず、閲覧専用のブログ(コメントはメール等で受け取る)
> 2. アクセスしたユーザーからページ上に認証なしのコメントが投稿できるブログ
> 3. ログインをするとどんなユーザーでも記事が書き込めて、コメントも書き込みができるブログ
> 
> 例えばこの中でどれがやりたいかをまず決めて、その上でなにが必要かを洗い出していくといいと思う (パッと全体を見るとここが固まってないよう見えるから)

ありがとうございます。
2で考えていましたが、そこも明示化していませんでした。
そこもタスクとして起こし、必要なものを洗い出します。
