### ISSUE TITLE
フロントエンド/バックエンドの開発

### ISSUE THREAD

**Issue by fuzzy-yusuke** [fuzzy-yusuke/tasks#23]
実践Node.js第7章

**Comment by fuzzy-yusuke** [comment]
Reactの概要と基本的な操作が一通り載ってた
以前受講した挫折しないReact講座のおかげで頭には入りやすかったが、やっぱりコンポーネントやDOMなどの概念は難しい...
慣れも必要？

**Comment by fuzzy-yusuke** [comment]
process.envでポートを指定するやり方が出てきた
ターミナルでポートを指定したら、「PORT=なんてコマンドはありません」と出た
process.envを確認すると、PORTの項目が無かった
これが原因なのか...？
process.envでポートを指定する時は新しく環境変数としてPORTの項目を追加しなければならないのか？

**Comment by sena-v** [comment]
7.8.1のラストのところならこの筆者的になんかツールが入ってて、それが原因で省略されてるとかの気もするけど方法はいろいろあるからそっちで設定するといいかも(他のサイトでもできてるからバージョン差の可能性もあるけど)

https://www.twilio.com/ja/blog/working-with-environment-variables-in-node-js-html-jp

ただここだけの話だと環境変数がどうこうってよりポートが変更したいだけならapp.listen(8000, () => {...})ってベタ書きでも影響なさそうかな

**Comment by fuzzy-yusuke** [comment]
> 7.8.1のラストのところならこの筆者的になんかツールが入ってて、それが原因で省略されてるとかの気もするけど方法はいろいろあるからそっちで設定するといいかも(他のサイトでもできてるからバージョン差の可能性もあるけど)
> 
> https://www.twilio.com/ja/blog/working-with-environment-variables-in-node-js-html-jp
> 
> ただここだけの話だと環境変数がどうこうってよりポートが変更したいだけならapp.listen(8000, () => {...})ってベタ書きでも影響なさそうかな

ありがとうございます！
一旦ベタ書きで設定し、少し調べてみます。

**Comment by fuzzy-yusuke** [comment]
一旦ベタ書きすると、接続できた。
しかし、getUsersメソッドからコンソールで値を取得しようとすると、「SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON」とエラーを吐いた
調べると、「json形式でデータを取得しようとしたのに、HTML形式で値を取得してしまっている可能性が高い」ことが分かったが、具体的な解決方法の画策や書籍のコードと比較しても差異が無かった

```
import { useState } from 'react';
import './App.css';

function User({ name }) {
  return <li style={{ padding: '8px'}}>{name}</li>
}

const getUsers = async() => {
  const response = await fetch('/api/users');
  const body = response.json();
  return body;
}

function App() {
  const [users, setUsers] = useState(['alpha','bravo','charlie','delta']);
  const  [inputText, setInputText] = useState('');

  getUsers()
    .then((data) => console.log(data))
    .catch((error) => console.error(error));

  const userList = users.map((user) => {
    return <User key={user} name={user} />;
  });
```

**Comment by fuzzy-yusuke** [comment]
取り急ぎこのまま進めた
http-proxy-middlewareはインストールしようとしたら「To address all issues (including breaking changes), run:
  npm audit fix --force」と出たので、「npm audit fix --force」を実行したが、同じエラーが出た
このまま進めたが、フロントエンドが立ち上がらなくなった
何なんだこれ...

**Comment by sena-v** [comment]
` run:
npm audit fix --force`自体はバグじゃなくて警告だから無視していいやつだと思う

nodeの良いところ(でもあり悪いところでもある)けど、アップデートがめちゃくちゃ頻繁に実施されて
バグとか脆弱性対応があるからnpmの実行時に今使ってるツール群のアプデチェックが自動で走って、アプデ推奨の場合
上のログが出る事がある(バグ対応したからアプデしてくれ)

`npm audit fix --force`自体は詳しく自分で調べたほうが良いと思うけど(まぁforcet付いてるし)
今回のだけだと多分package.jsonの更新差分を消して動いてた状態に戻して、`npm i http-proxy-middleware`した時に
`To address all issues (including breaking changes), run:
npm audit fix --force`を無視して進めるのが一番早いと思う

**Comment by fuzzy-yusuke** [comment]
ありがとうございます。
こちらは警告なのですね。
auditコマンドについても少し調べ、先に進めます。

**Comment by fuzzy-yusuke** [comment]
以下の注意書きが出たので、試したが、フロントエンドの立ち上がりが失敗する事象は解決しなかった
6については、ディレクトリが無かったので、一番上の階層にbabel-jestをインストールした

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\git\monorepo_test\node_modules\babel-jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

**Comment by fuzzy-yusuke** [comment]
Nodeのバージョンを一旦アプデし、nvmでダウングレードしたら解決できた
あと、記載されていないが、Reactのimportの記述はしっかりすること

**Comment by fuzzy-yusuke** [comment]
フロントエンドのテスト、App.test.jsの記述が誤っていた
functionはApp.jsに記載すればOK
App.test.jsにはテストコードだけ書けばOK

**Comment by fuzzy-yusuke** [comment]
記述と違うところが多かったが、ユニットテストのお作法や重要性を改めて認識することができた
現場でもテストコードを書いているので、仕事に活かしていこう
